// let startBtn = document.getElementById('start'); 
// let stopBtn = document.getElementById('stop');
// let resBtn = document.getElementById('reset');


// var Interval = setInterval(Timer,1000);
//var NewInterval = setInterval(greet,6000);
// let i = 0;


// function Timer() {
//   document.getElementById("demo").innerHTML = i;
//   i++;
// }
// document.getElementById('stop').addEventListener('click',function(){
//     clearInterval(Interval);
//     Interval = null; 
// })
// document.getElementById('start').addEventListener('click',function(){
//     Interval = setInterval(Timer, 1000);
//     greet();
    
// })
// document.getElementById('reset').addEventListener('click',function(){
//    // clearInterval;
//     //Interval = null; 

// })

// // function greet(){
// //     const helloMess = document.querySelector(".hello-message");
// //     helloMess.textContent+="hello";
    
// // }
// // setInterval(greet,6000);




// // const names = document.querySelector("#name")

// // let getName = async()=>{
// //     let response = await fetch("https://jsonplaceholder.typicode.com/users");
// //     let data = await response.json();

// //     //return data
// //     console.log(data)
// //     const NewNames= data.map((username)=>(username.name))
// //     console.log(NewNames)
// // };
// // const dataName = getName()



// // let getName = async()=>{
// //     let response = await fetch("https://jsonplaceholder.typicode.com/users");
// //     let data = await response.json();
// //     console.log(data);
// // //     const NewNames = data.map((username)=>(username.name));
// // // console.log(NewNames)
// // // }

// // // //getName();
// // const NewName = data.map((uresrname)=>(username.name))
// // }

// // program where the user has to guess a number generated by a program

//  function guessNumber() {

//     // generating a random integer from 1 to 10
//     const random = Math.floor(Math.random() * 10) ;

//     // take input from the user
//     let number = parseInt(prompt('Guess a number from 1 to 10: '));

//     // take the input until the guess is correct
//     while(number !== random) {
//         number = parseInt(prompt('Guess a number from 1 to 10: '));
//     }

//     // check if the guess is correct
//     if(number == random) {
//         console.log('You guessed the correct number.');
//     }

// }

 
// guessNumber();

(async () => {
    const url = 'https://jsonplaceholder.typicode.com/posts';
    const data = { 
           title: 'foo',
            body: 'bar',
            userId: 1,
};
  
    try {
      const responseData = await postData(url, data); // Post data to the URL
      console.log('Response data:', responseData);
      // Do something with the response data
    } catch (error) {
      // Handle errors
      console.error('Error:', error);
    }
  })
//   console.log(data)

  